package org.skyfaced.noti.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val lightPrimary = Color(0xFF0861A4)
private val lightOnPrimary = Color(0xFFFFFFFF)
private val lightPrimaryContainer = Color(0xFFD2E4FF)
private val lightOnPrimaryContainer = Color(0xFF001C37)
private val lightSecondary = Color(0xFF535F70)
private val lightOnSecondary = Color(0xFFFFFFFF)
private val lightSecondaryContainer = Color(0xFFD7E3F8)
private val lightOnSecondaryContainer = Color(0xFF101C2B)
private val lightTertiary = Color(0xFF006A68)
private val lightOnTertiary = Color(0xFFFFFFFF)
private val lightTertiaryContainer = Color(0xFF6FF7F4)
private val lightOnTertiaryContainer = Color(0xFF00201F)
private val lightError = Color(0xFFBA1A1A)
private val lightErrorContainer = Color(0xFFFFDAD6)
private val lightOnError = Color(0xFFFFFFFF)
private val lightOnErrorContainer = Color(0xFF410002)
private val lightBackground = Color(0xFFFDFCFF)
private val lightOnBackground = Color(0xFF1A1C1E)
private val lightSurface = Color(0xFFFDFCFF)
private val lightOnSurface = Color(0xFF1A1C1E)
private val lightSurfaceVariant = Color(0xFFDFE2EB)
private val lightOnSurfaceVariant = Color(0xFF43474E)
private val lightOutline = Color(0xFF73777F)
private val lightInverseOnSurface = Color(0xFFF1F0F4)
private val lightInverseSurface = Color(0xFF2F3033)
private val lightInversePrimary = Color(0xFF9FCAFF)
private val lightShadow = Color(0xFF000000)
private val lightSurfaceTint = Color(0xFF0861A4)

private val darkPrimary = Color(0xFF9FCAFF)
private val darkOnPrimary = Color(0xFF003259)
private val darkPrimaryContainer = Color(0xFF00497E)
private val darkOnPrimaryContainer = Color(0xFFD2E4FF)
private val darkSecondary = Color(0xFFBBC7DB)
private val darkOnSecondary = Color(0xFF253140)
private val darkSecondaryContainer = Color(0xFF3C4858)
private val darkOnSecondaryContainer = Color(0xFFD7E3F8)
private val darkTertiary = Color(0xFF4DDAD7)
private val darkOnTertiary = Color(0xFF003736)
private val darkTertiaryContainer = Color(0xFF00504F)
private val darkOnTertiaryContainer = Color(0xFF6FF7F4)
private val darkError = Color(0xFFFFB4AB)
private val darkErrorContainer = Color(0xFF93000A)
private val darkOnError = Color(0xFF690005)
private val darkOnErrorContainer = Color(0xFFFFDAD6)
private val darkBackground = Color(0xFF1A1C1E)
private val darkOnBackground = Color(0xFFE2E2E6)
private val darkSurface = Color(0xFF1A1C1E)
private val darkOnSurface = Color(0xFFE2E2E6)
private val darkSurfaceVariant = Color(0xFF43474E)
private val darkOnSurfaceVariant = Color(0xFFC3C6CF)
private val darkOutline = Color(0xFF8D9199)
private val darkInverseOnSurface = Color(0xFF1A1C1E)
private val darkInverseSurface = Color(0xFFE2E2E6)
private val darkInversePrimary = Color(0xFF0861A4)
private val darkShadow = Color(0xFF000000)
private val darkSurfaceTint = Color(0xFF9FCAFF)

val NotiLightColorScheme = lightColorScheme(
    primary = lightPrimary,
    onPrimary = lightOnPrimary,
    primaryContainer = lightPrimaryContainer,
    onPrimaryContainer = lightOnPrimaryContainer,
    secondary = lightSecondary,
    onSecondary = lightOnSecondary,
    secondaryContainer = lightSecondaryContainer,
    onSecondaryContainer = lightOnSecondaryContainer,
    tertiary = lightTertiary,
    onTertiary = lightOnTertiary,
    tertiaryContainer = lightTertiaryContainer,
    onTertiaryContainer = lightOnTertiaryContainer,
    error = lightError,
    onError = lightOnError,
    errorContainer = lightErrorContainer,
    onErrorContainer = lightOnErrorContainer,
    background = lightBackground,
    onBackground = lightOnBackground,
    surface = lightSurface,
    onSurface = lightOnSurface,
    surfaceVariant = lightSurfaceVariant,
    onSurfaceVariant = lightOnSurfaceVariant,
    outline = lightOutline,
    inverseSurface = lightInverseSurface,
    inverseOnSurface = lightInverseOnSurface,
    inversePrimary = lightInversePrimary,
    surfaceTint = lightSurfaceTint,
)

val NotiDarkColorScheme = darkColorScheme(
    primary = darkPrimary,
    onPrimary = darkOnPrimary,
    primaryContainer = darkPrimaryContainer,
    onPrimaryContainer = darkOnPrimaryContainer,
    secondary = darkSecondary,
    onSecondary = darkOnSecondary,
    secondaryContainer = darkSecondaryContainer,
    onSecondaryContainer = darkOnSecondaryContainer,
    tertiary = darkTertiary,
    onTertiary = darkOnTertiary,
    tertiaryContainer = darkTertiaryContainer,
    onTertiaryContainer = darkOnTertiaryContainer,
    error = darkError,
    onError = darkOnError,
    errorContainer = darkErrorContainer,
    onErrorContainer = darkOnErrorContainer,
    background = darkBackground,
    onBackground = darkOnBackground,
    surface = darkSurface,
    onSurface = darkOnSurface,
    surfaceVariant = darkSurfaceVariant,
    onSurfaceVariant = darkOnSurfaceVariant,
    outline = darkOutline,
    inverseSurface = darkInverseSurface,
    inverseOnSurface = darkInverseOnSurface,
    inversePrimary = darkInversePrimary,
    surfaceTint = darkSurfaceTint,
)